import Head from "next/head";
import Navbar from "../components/Navbar";
import HeroSection from "../components/Index-page/HeroSection";

export default function Home() {
  return (
    <>
      <Navbar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
    </>
  );
}
